# configuration for oauth provider and app registration
spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/organizations/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        registration:
          advisor-app:
            provider: azure-ad
            client-id: <your-client-id>
            client-secret: <your-client-secret>
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:4200/oauth2/msclient/advisor/redirect
            scope: openid,profile
server:
  forward-headers-strategy: native